version: '3.8'

services:
  open-interpreter:
    build: .
    container_name: open-interpreter
    env_file:
      - .env
    volumes:
      - .:/workspace
    command: /bin/bash -c "echo 'Container is running...'; tail -f /dev/null"
